client
dev-type tun
dev tunx
proto udp
tun-mtu 1400
cipher BF-CBC
remote 770071.xyz 1194
resolv-retry infinite
nobind
persist-key
persist-tun
verb 3
auth-user-pass
script-security 2

<ca>
-----BEGIN CERTIFICATE-----
MIIDQTCCAimgAwIBAgIJAI568o1SNdCSMA0GCSqGSIb3DQEBCwUAMDcxCzAJBgNV
BAYTAkNOMQ4wDAYDVQQKDAVpS3VhaTEYMBYGA1UEAwwPaUt1YWkgRGV2aWNlIENB
MB4XDTI0MDEyMzA5MzY0M1oXDTM0MDEyMDA5MzY0M1owNzELMAkGA1UEBhMCQ04x
DjAMBgNVBAoMBWlLdWFpMRgwFgYDVQQDDA9pS3VhaSBEZXZpY2UgQ0EwggEiMA0G
CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDfaUDLLqkFAHdSroAzQUIU9Nb//64V
PzvUgZCf+MGLQzVcQ7JoONpDJKmEJfFAV8QTUEcSjw7dsdcyTUf0CvI5QnWWqjX+
vFnCaDCklVm6uJwUNWEtic8WXA/DE8jVQy5ke8PwPc/x2LcCiwPVZbEq0e8Uxakz
WKa3IJ6NGIQm17FDAZN1OFokHmRm/RcSLhrz/piqeGhMlw4MYr/WjoXUEZSCsunu
qG7rplov9whckSRYmV6yUg6RE/cb8Fy+aS4QfAMSRjgdw9VCRXXKEyJsGUVcwVem
Y1jBnuj6/AYRII9DNnMzE1Vkm96rLog5tMCnx3XOADrUiEiskFC3On49AgMBAAGj
UDBOMB0GA1UdDgQWBBSNBiZBNV2uGOX223eoQYah/L3qGDAfBgNVHSMEGDAWgBSN
BiZBNV2uGOX223eoQYah/L3qGDAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUA
A4IBAQAGqSNTnshDv7TULFdou/VKQXTc7etK8EoP+0Y1//3qzs3ZK7pnnm0OvFIb
GtRIpPRmeWt4EIJUkymKSkM/+sm3/Yh2jkcUoI5YGrGGph3ky1Sgk3Q9gY6HfKXb
eiWrAxh0dufn3f2m5ma4GmQc1u/rZL8bzM6pXwqiWKfAjZt1NyrK7bc26Xp/S8iQ
UJwnrSQIE7iPVVdUxZ9QMeQPr5PCsJEmg7/UKnL8w//0wTLkSCJKTKK3PpKJOuy1
DtSkQf2TepE/0Kwy8kOm6ZpN6Sf5gulBjhI2vu8ILQMl1tqDUpOQLxO6fX3OFRxF
Tmv4Qp0AIruP3deMxqPfYL84isTi
-----END CERTIFICATE-----

</ca>

# redirect-gateway def1 bypass-dns  # uncomment to set as default gateway
# route-nopull  # uncomment to disable server route push
#
